import streamlit as st
import pandas as pd
import plotly.express as px

from data import load_sales_data


# ==========================================
# PAGE SETTINGS
# ==========================================

st.set_page_config(
    page_title="Sales Analytics",
    page_icon="📈",
    layout="wide"
)


# ==========================================
# CUSTOM CSS
# ==========================================

st.markdown("""
<style>

    /* Main page */
    .main {
        padding-top: 1.5rem;
    }


    /* Page header */
    .analytics-title {
        font-size: 42px;
        font-weight: 700;
        margin-bottom: 5px;
    }

    .analytics-subtitle {
        font-size: 18px;
        margin-bottom: 30px;
    }


    /* KPI cards */
    div[data-testid="stMetric"] {
        padding: 20px;
        border-radius: 14px;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background-color: rgba(128, 128, 128, 0.08);
        transition: transform 0.2s ease;
    }

    div[data-testid="stMetric"]:hover {
        transform: translateY(-3px);
    }


    /* Section headings */
    .section-title {
        font-size: 25px;
        font-weight: 650;
        margin-top: 15px;
        margin-bottom: 15px;
    }


    /* Information cards */
    .info-card {
        padding: 20px;
        border-radius: 14px;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background-color: rgba(128, 128, 128, 0.06);
        margin-bottom: 15px;
    }


    /* Sidebar */
    section[data-testid="stSidebar"] {
        padding-top: 2rem;
    }


    /* Divider */
    hr {
        margin-top: 30px;
        margin-bottom: 30px;
    }


    /* Footer */
    .analytics-footer {
        text-align: center;
        padding: 20px;
        margin-top: 25px;
        font-size: 14px;
        opacity: 0.7;
    }

</style>
""", unsafe_allow_html=True)


# ==========================================
# LOAD DATA
# ==========================================

try:

    df = load_sales_data()

except FileNotFoundError as e:

    st.error(f"❌ {e}")
    st.stop()

except ValueError as e:

    st.error(f"❌ {e}")
    st.stop()


# ==========================================
# PAGE HEADER
# ==========================================

st.markdown(
    '<div class="analytics-title">'
    '📈 Sales Analytics'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="analytics-subtitle">'
    'Explore your sales performance through interactive analytics.'
    '</div>',
    unsafe_allow_html=True
)


# ==========================================
# KPI CALCULATIONS
# ==========================================

total_revenue = df["Revenue"].sum()

total_orders = df["Order_ID"].nunique()

total_units = df["Quantity"].sum()

average_order = (
    total_revenue / total_orders
    if total_orders > 0
    else 0
)


# ==========================================
# KPI CARDS
# ==========================================

col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "Total Revenue",
        f"Rs. {total_revenue:,.0f}"
    )


with col2:

    st.metric(
        "Total Orders",
        f"{total_orders:,}"
    )


with col3:

    st.metric(
        "Units Sold",
        f"{total_units:,}"
    )


with col4:

    st.metric(
        "Average Order",
        f"Rs. {average_order:,.0f}"
    )


# ==========================================
# PRODUCT PERFORMANCE
# ==========================================

st.divider()

st.markdown(
    '<div class="section-title">'
    '💻 Product Performance'
    '</div>',
    unsafe_allow_html=True
)


product_revenue = (
    df
    .groupby("Product")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)


fig_product = px.bar(
    product_revenue,
    x="Product",
    y="Revenue",
    title="Revenue Generated by Product",
    text_auto=True
)


fig_product.update_layout(
    xaxis_title="Product",
    yaxis_title="Revenue (Rs.)",
    hovermode="x",
    margin=dict(
        l=20,
        r=20,
        t=60,
        b=20
    )
)


st.plotly_chart(
    fig_product,
    use_container_width=True
)


# ==========================================
# REGION + SALESPERSON
# ==========================================

col1, col2 = st.columns(2)


# ==========================================
# REGIONAL PERFORMANCE
# ==========================================

with col1:

    st.markdown(
        '<div class="section-title">'
        '🌍 Regional Performance'
        '</div>',
        unsafe_allow_html=True
    )


    region_revenue = (
        df
        .groupby("Region")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )


    fig_region = px.bar(
        region_revenue,
        x="Region",
        y="Revenue",
        title="Revenue by Region",
        text_auto=True
    )


    fig_region.update_layout(
        xaxis_title="Region",
        yaxis_title="Revenue (Rs.)",
        margin=dict(
            l=20,
            r=20,
            t=60,
            b=20
        )
    )


    st.plotly_chart(
        fig_region,
        use_container_width=True
    )


# ==========================================
# SALESPERSON PERFORMANCE
# ==========================================

with col2:

    st.markdown(
        '<div class="section-title">'
        '👤 Salesperson Performance'
        '</div>',
        unsafe_allow_html=True
    )


    salesperson_revenue = (
        df
        .groupby("Salesperson")["Revenue"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )


    fig_salesperson = px.bar(
        salesperson_revenue,
        x="Salesperson",
        y="Revenue",
        title="Revenue by Salesperson",
        text_auto=True
    )


    fig_salesperson.update_layout(
        xaxis_title="Salesperson",
        yaxis_title="Revenue (Rs.)",
        margin=dict(
            l=20,
            r=20,
            t=60,
            b=20
        )
    )


    st.plotly_chart(
        fig_salesperson,
        use_container_width=True
    )


# ==========================================
# REVENUE TREND
# ==========================================

st.divider()

st.markdown(
    '<div class="section-title">'
    '📈 Revenue Trend'
    '</div>',
    unsafe_allow_html=True
)


daily_revenue = (
    df
    .groupby("Date")["Revenue"]
    .sum()
    .reset_index()
)


fig_trend = px.line(
    daily_revenue,
    x="Date",
    y="Revenue",
    title="Daily Revenue Trend",
    markers=True
)


fig_trend.update_layout(
    xaxis_title="Date",
    yaxis_title="Revenue (Rs.)",
    hovermode="x unified",
    margin=dict(
        l=20,
        r=20,
        t=60,
        b=20
    )
)


st.plotly_chart(
    fig_trend,
    use_container_width=True
)


# ==========================================
# TOP PRODUCT
# ==========================================

st.divider()

st.markdown(
    '<div class="section-title">'
    'Top Product'
    '</div>',
    unsafe_allow_html=True
)


top_product = (
    product_revenue
    .sort_values(
        "Revenue",
        ascending=False
    )
    .iloc[0]
)


st.markdown(
    '<div class="info-card">',
    unsafe_allow_html=True
)

st.metric(
    "Highest Revenue Product",
    top_product["Product"],
    f"Rs. {top_product['Revenue']:,.0f}"
)

st.markdown(
    '</div>',
    unsafe_allow_html=True
)


# ==========================================
# FOOTER
# ==========================================

st.markdown(
    """
    <div class="analytics-footer">
        📊 Taqi Sales Dashboard &nbsp;•&nbsp;
        📈 Sales Analytics &nbsp;•&nbsp;
        🐍 Python + Pandas + Streamlit + Plotly
    </div>
    """,
    unsafe_allow_html=True
)