import streamlit as st


# ==========================================
# PAGE SETTINGS
# ==========================================

st.set_page_config(
    page_title="About Taqi Sales Dashboard",
    page_icon="ℹ️",
    layout="wide"
)


# ==========================================
# CUSTOM CSS
# ==========================================

st.markdown("""
<style>

    /* Main page */
    .main {
        padding-top: 1.5rem;
    }


    /* Page title */
    .about-title {
        font-size: 42px;
        font-weight: 700;
        margin-bottom: 5px;
    }


    /* Page subtitle */
    .about-subtitle {
        font-size: 18px;
        margin-bottom: 30px;
    }


    /* Section titles */
    .section-title {
        font-size: 25px;
        font-weight: 650;
        margin-top: 15px;
        margin-bottom: 15px;
    }


    /* Information cards */
    .info-card {
        padding: 20px;
        border-radius: 14px;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background-color: rgba(128, 128, 128, 0.06);
        margin-bottom: 15px;
    }


    /* Feature cards */
    .feature-card {
        padding: 18px;
        border-radius: 12px;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background-color: rgba(128, 128, 128, 0.06);
        margin-bottom: 12px;
        min-height: 70px;
    }


    /* Technology cards */
    .tech-card {
        padding: 18px;
        border-radius: 12px;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background-color: rgba(128, 128, 128, 0.06);
        margin-bottom: 12px;
    }


    /* Sidebar */
    section[data-testid="stSidebar"] {
        padding-top: 2rem;
    }


    /* Footer */
    .about-footer {
        text-align: center;
        padding: 25px;
        margin-top: 30px;
        font-size: 14px;
        opacity: 0.7;
    }

</style>
""", unsafe_allow_html=True)


# ==========================================
# PAGE HEADER
# ==========================================

st.markdown(
    '<div class="about-title">'
    'ℹ️ About Taqi Sales Dashboard'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="about-subtitle">'
    'A Python-powered interactive sales analytics project.'
    '</div>',
    unsafe_allow_html=True
)


# ==========================================
# PROJECT OVERVIEW
# ==========================================

st.markdown(
    '<div class="section-title">'
    '📊 Project Overview'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="info-card">
        <strong>Taqi Sales Dashboard</strong> is an interactive
        sales analytics application built with Python.
        <br><br>
        The project takes raw sales records from a CSV file,
        processes them using Pandas, and presents useful
        business information through an interactive Streamlit
        dashboard.
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================
# PROJECT FEATURES
# ==========================================

st.markdown(
    '<div class="section-title">'
    '✨ Key Features'
    '</div>',
    unsafe_allow_html=True
)

features = [
    ("📊", "Interactive Dashboard",
     "View important sales information in one place."),

    ("📅", "Date Filtering",
     "Analyze sales by different time periods."),

    ("💻", "Product Analysis",
     "Compare revenue generated by different products."),

    ("🌍", "Regional Analysis",
     "Explore sales performance across regions."),

    ("👤", "Salesperson Analysis",
     "Analyze revenue generated by each salesperson."),

    ("📈", "Interactive Charts",
     "Visualize sales trends using Plotly."),

    ("📋", "Sales Data Table",
     "View and filter individual sales records."),

    ("📥", "CSV Export",
     "Download filtered sales data as a CSV file."),

    ("📑", "Multi-Page Application",
     "Navigate between Dashboard, Analytics, Sales Data, and About.")
]


# Create feature cards in columns

for i in range(0, len(features), 3):

    columns = st.columns(3)

    for column, feature in zip(
        columns,
        features[i:i + 3]
    ):

        icon, title, description = feature

        with column:

            st.markdown(
                f"""
                <div class="feature-card">
                    <h3>{icon} {title}</h3>
                    <p>{description}</p>
                </div>
                """,
                unsafe_allow_html=True
            )


# ==========================================
# TECHNOLOGIES
# ==========================================

st.divider()

st.markdown(
    '<div class="section-title">'
    '🛠️ Technologies Used'
    '</div>',
    unsafe_allow_html=True
)

technologies = [
    (
        "🐍 Python",
        "Main programming language used to build the project."
    ),

    (
        "🐼 Pandas",
        "Used for loading, cleaning, processing, and analyzing data."
    ),

    (
        "🎈 Streamlit",
        "Used to create the interactive web dashboard."
    ),

    (
        "📊 Plotly",
        "Used to create interactive charts and visualizations."
    ),

    (
        "📄 CSV",
        "Used as the source format for storing sales records."
    )
]


for technology, purpose in technologies:

    st.markdown(
        f"""
        <div class="tech-card">
            <strong>{technology}</strong>
            <br>
            {purpose}
        </div>
        """,
        unsafe_allow_html=True
    )


# ==========================================
# DATASET
# ==========================================

st.divider()

st.markdown(
    '<div class="section-title">'
    '📁 Dataset'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="info-card">
        The dashboard uses a sales CSV dataset containing
        information about:
        <br><br>
        📅 Date &nbsp; • &nbsp;
        🧾 Order ID &nbsp; • &nbsp;
        💻 Product &nbsp; • &nbsp;
        🏷️ Category
        <br>
        🌍 Region &nbsp; • &nbsp;
        📦 Quantity &nbsp; • &nbsp;
        💰 Price &nbsp; • &nbsp;
        👤 Salesperson
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================
# PROJECT GOAL
# ==========================================

st.markdown(
    '<div class="section-title">'
    '🎯 Project Goal'
    '</div>',
    unsafe_allow_html=True
)

st.markdown(
    """
    <div class="info-card">
        The goal of this project is to demonstrate how raw
        sales data can be transformed into meaningful
        information using Python and data-analysis tools.
        <br><br>
        It combines data cleaning, calculations, filtering,
        visualization, and web-dashboard development into
        one complete project.
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================
# PROJECT STRUCTURE
# ==========================================

st.markdown(
    '<div class="section-title">'
    '📂 Project Structure'
    '</div>',
    unsafe_allow_html=True
)

st.code(
    """
Taqi_Sales_Dashboard/
│
├── app.py
├── data.py
├── sales.csv
├── requirements.txt
├── venv/
│
└── pages/
    ├── 1_Analytics.py
    ├── 2_Sales_Data.py
    └── 3_About.py
""",
    language="text"
)


# ==========================================
# FOOTER
# ==========================================

st.divider()

st.markdown(
    """
    <div class="about-footer">
        📊 Taqi Sales Dashboard
        &nbsp;•&nbsp;
        🐍 Python
        &nbsp;•&nbsp;
        🐼 Pandas
        &nbsp;•&nbsp;
        🎈 Streamlit
        &nbsp;•&nbsp;
        📈 Plotly
        <br><br>
        Built as a complete Python data-analysis project.
    </div>
    """,
    unsafe_allow_html=True
)